name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        arch: 'linux_gcc_64'

    - name: Build project
      run: |
        mkdir build
        cd build
        qmake ../pari.pro
        make

    - name: Run unit tests
      run: |
        cd build/tests
        ./tst_settings

    - name: Run smoke test
      run: |
        cd build/src
        ./pari --selfcheck
