name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcb-randr0 xvfb

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        arch: 'linux_gcc_64'
        modules: 'qt5compat qtshadertools'

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run unit tests
      working-directory: build/tests
      run: |
        QT_QPA_PLATFORM=offscreen ./tst_all

    - name: Run UI tests
      run: |
        # Use full path for input to ensure discovery
        QML_IMPORT_PATH=$(pwd)/build/3rdparty QML2_IMPORT_PATH=$(pwd)/build/3rdparty xvfb-run --server-args="-screen 0 1024x768x24" ./build/tests/tst_ui -input $(pwd)/tests

    - name: Run smoke test
      working-directory: build/src
      run: |
        QML_IMPORT_PATH=$(pwd)/../3rdparty QML2_IMPORT_PATH=$(pwd)/../3rdparty QT_QPA_PLATFORM=offscreen ./pari --selfcheck
